using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

[assembly: AssemblyTitle("StarWar.Console")]
[assembly: AssemblyDescription("Generated by PL.DynamicsCrm.DevKit - 2.0.0 - https://github.com/phuocle/Dynamics-Crm-DevKit")]
#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("StarWar.Console")]
[assembly: AssemblyCopyright("Copyright © 2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: SecurityRules(SecurityRuleSet.Level2)]
[assembly: ComVisible(false)]
[assembly: Guid("baa83f10-a103-4226-b802-8c9349e004e8")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
