using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Facebook.Vietnam.Hcm.Console.365.462")]
[assembly: AssemblyDescription("Generated by PL.DynamicsCrm.DevKit - 2.0.0 - https://github.com/phuocle/Dynamics-Crm-DevKit")]
#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Facebook.Vietnam.Hcm.Console.365.462")]
[assembly: AssemblyCopyright("Copyright © 2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("2a0d04d2-e08e-4cf8-9e92-035b630bc452")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
