using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Facebook.Vietnam.Hcm.Workflow.Account.2011.40")]
[assembly: AssemblyDescription("Generated by PL.DynamicsCrm.DevKit - 2.0.0 - https://github.com/phuocle/Dynamics-Crm-DevKit")]
#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Facebook.Vietnam.Hcm.Workflow.Account.2011.40")]
[assembly: AssemblyCopyright("Copyright © 2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("en")]
[assembly: ComVisible(false)]
[assembly: Guid("463cea6e-4afc-4a14-be61-35f642129c2a")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
