using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Facebook.Vietnam.Hcm.CustomAction.Account.2011.40")]
[assembly: AssemblyDescription("Generated by PL.DynamicsCrm.DevKit - 2.0.0 - https://github.com/phuocle/Dynamics-Crm-DevKit")]
#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Facebook.Vietnam.Hcm.CustomAction.Account.2011.40")]
[assembly: AssemblyCopyright("Copyright © 2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("en")]
[assembly: ComVisible(false)]
[assembly: Guid("d61870a1-51b4-4437-a41f-ac5da5c9a6c6")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
