using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Facebook.Vietnam.Hcm.WebResource.2011.40")]
[assembly: AssemblyDescription("Generated by PL.DynamicsCrm.DevKit - 2.0.0 - https://github.com/phuocle/Dynamics-Crm-DevKit")]
#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Facebook.Vietnam.Hcm.WebResource.2011.40")]
[assembly: AssemblyCopyright("Copyright © 2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("en")]
[assembly: ComVisible(false)]
[assembly: Guid("fe3039d2-7ee9-49ba-869e-de2e9c36d3c6")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
