using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

[assembly: AssemblyTitle("StarWar.UiTest")]
[assembly: AssemblyDescription("Generated by PL.DynamicsCrm.DevKit - 2.0.0 - https://github.com/phuocle/Dynamics-Crm-DevKit")]
#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("StarWar.UiTest")]
[assembly: AssemblyCopyright("Copyright © 2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("en")]
[assembly: SecurityRules(SecurityRuleSet.Level2)]
[assembly: ComVisible(false)]
[assembly: Guid("127c17a9-20a4-48b8-bc82-693a18e59d91")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
